language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
install: /bin/true
script: "mvn clean install"
notifications:
  email:
    recipients:
      - aosleonardo@gmail.com
    on_success: change
    on_failure: change